export type SupportedLanguage = 'en' | 'hi' | 'ta';

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Brand & Nav
    portal_title: "AyushSkillBridge",
    portal_tagline: "Ministry of Ayush – AIIA (SIH26044)",
    nav_ayursetu: "AYURSETU",
    nav_colleges: "Verified Colleges",
    nav_verify: "Verify Ayush ID",
    nav_home: "Home",
    nav_assessment: "Skill Assessment",
    nav_gap_analysis: "Gap Analysis",
    nav_opportunities: "Opportunities",
    nav_applications: "Applications",
    nav_logbook: "e-Logbook",
    nav_passport: "Skill Passport",
    nav_org_portal: "Industry Portal",
    nav_dept_dashboard: "Department Dashboard",
    nav_admin: "Ministry Admin",
    switch_persona: "Switch Persona (Demo)",

    // Landing Page
    hero_badge: "Smart India Hackathon 2026 • SIH26044",
    hero_title: "Academia–Industry Collaboration for Ayush Skills, Internships & Verified Placement",
    hero_subtitle: "Bridging the gap between Ayush medical curricula and modern industry requirements with AI skill ontology, CBME e-Logbooks, and W3C Verifiable Credentials.",
    cta_get_started: "Get Started as Student",
    cta_explore_opps: "Browse Internships",
    cta_post_opp: "Post Opportunity (Industry)",
    stat_students: "2,400+ Active Students",
    stat_institutions: "120+ Ayush Colleges",
    stat_industry: "85+ Verified Partners",
    stat_credentials: "4,100+ Issued Credentials",

    // Onboarding
    onboard_title: "Student Onboarding & Identity Consent",
    onboard_subtitle: "Align with Ayush Grid & ABDM protocols with full consent control.",
    label_fullname: "Full Name",
    label_email: "Email Address",
    label_phone: "Phone Number",
    label_stream: "Ayush Stream",
    label_year: "Current Academic Year",
    label_city: "City",
    label_state: "State",
    label_abha_id: "ABHA ID (Ayushman Bharat Health Account)",
    abha_placeholder: "91-4521-8890-1234",
    abha_verify_btn: "Verify with ABHA",
    abha_verified_badge: "ABHA Identity Verified",
    consent_section_title: "Ayush Grid Data Sharing & Privacy Consents",
    consent_share_profile: "Share anonymized profile with accredited Ayush Hospitals & Labs",
    consent_share_skills: "Share verified skill assessment vectors with verified recruiters",
    consent_analytics: "Allow anonymized usage in Ministry of Ayush national workforce analytics",
    btn_save_continue: "Save & Proceed to Assessment",

    // Assessment
    assessment_title: "Adaptive Ayush Skill Assessment",
    assessment_subtitle: "Evaluate clinical procedures, pharmacological standardization, and digital health competencies.",
    q_panchakarma: "How confident are you in setting up and calibrating Shirodhara oil flow and temperature?",
    q_nadi: "Can you identify Gati and Tridosha imbalances through radial Nadi Pariksha?",
    q_hplc: "Have you operated HPLC or HPTLC for marker compound quantification in herbal extracts?",
    q_gmp: "Are you familiar with Schedule T GMP documentation and Batch Manufacturing Records (BMR)?",
    q_emr: "Have you entered clinical morbidity data into Ayush Grid / NAMASTE Portal compliant systems?",
    lvl_none: "None / No Exposure",
    lvl_basic: "Basic (Observed)",
    lvl_intermediate: "Intermediate (Assisted)",
    lvl_advanced: "Advanced (Performed under Supervision)",
    lvl_expert: "Expert (Independent Mastery)",
    btn_submit_assessment: "Submit Assessment & Generate Readiness Vector",

    // Opportunities & Filters
    filter_all: "All Opportunities",
    filter_internship: "Internships",
    filter_micro: "Micro-Internships (NSQF)",
    filter_faculty: "Faculty Training",
    filter_remote: "Remote Only",
    btn_apply: "1-Click Apply",
    btn_applied: "Applied",
    match_score: "AI Match Score",
    stipend_per_month: "/ month",
    duration_weeks: "weeks",

    // e-Logbook
    logbook_title: "Competency-Mapped e-Logbook (CBME / DOAP)",
    logbook_subtitle: "Demonstrate, Observe, Assist, Perform clinical case logs verified by faculty mentors.",
    btn_log_procedure: "Log Clinical Procedure",
    th_code: "Code",
    th_competency: "Competency Name",
    th_domain: "Domain",
    th_doap_level: "DOAP Level",
    th_count: "Procedures Count",
    th_status: "Mentor Verification",
    status_approved: "Approved by Faculty",
    status_pending: "Pending Review",
    privacy_notice: "Mandatory Privacy: I confirm that no patient-identifiable information (PHI) is included in this log."
  },

  hi: {
    // Brand & Nav
    portal_title: "आयुष स्किल ब्रिज",
    portal_tagline: "आयुष मंत्रालय – अखिल भारतीय आयुर्वेद संस्थान (SIH26044)",
    nav_ayursetu: "आयुर्सेतु",
    nav_colleges: "सत्यापित कॉलेज",
    nav_verify: "आईडी सत्यापन",
    nav_home: "होम",
    nav_assessment: "कौशल मूल्यांकन",
    nav_gap_analysis: "कौशल अंतर विश्लेषण",
    nav_opportunities: "अवसर एवं इंटर्नशिप",
    nav_applications: "मेरे आवेदन",
    nav_logbook: "ई-लॉगबुक",
    nav_passport: "स्किल पासपोर्ट",
    nav_org_portal: "उद्योग पोर्टल",
    nav_dept_dashboard: "विभाग डैशबोर्ड",
    nav_admin: "मंत्रालय एडमिन",
    switch_persona: "पात्र बदलें (डेमो)",

    // Landing Page
    hero_badge: "स्मार्ट इंडिया हैकथॉन 2026 • SIH26044",
    hero_title: "आयुष कौशल मैपिंग, इंटर्नशिप एवं सत्यापन हेतु शिक्षा-उद्योग सहयोग पोर्टल",
    hero_subtitle: "आयुष चिकित्सा पाठ्यक्रम और आधुनिक उद्योग आवश्यकताओं के बीच की खाई को एआई कौशल ऑन्टोलॉजी, सीबीएमई ई-लॉगबुक और W3C सत्यापन योग्य प्रमाणपत्रों से जोड़ना।",
    cta_get_started: "छात्र के रूप में शुरू करें",
    cta_explore_opps: "इंटर्नशिप खोजें",
    cta_post_opp: "अवसर पोस्ट करें (उद्योग)",
    stat_students: "2,400+ सक्रिय छात्र",
    stat_institutions: "120+ आयुष कॉलेज",
    stat_industry: "85+ सत्यापित साझेदार",
    stat_credentials: "4,100+ जारी किए गए प्रमाणपत्र",

    // Onboarding
    onboard_title: "छात्र ऑनबोर्डिंग एवं पहचान सहमति",
    onboard_subtitle: "आयुष ग्रिड और एबीडीएम प्रोटोकॉल के साथ पूर्ण सहमति नियंत्रण।",
    label_fullname: "पूरा नाम",
    label_email: "ईमेल पता",
    label_phone: "फ़ोन नंबर",
    label_stream: "आयुष संकाय",
    label_year: "वर्तमान शैक्षणिक वर्ष",
    label_city: "शहर",
    label_state: "राज्य",
    label_abha_id: "आभा आईडी (आयुष्मान भारत स्वास्थ्य खाता)",
    abha_placeholder: "91-4521-8890-1234",
    abha_verify_btn: "आभा से सत्यापित करें",
    abha_verified_badge: "आभा पहचान सत्यापित",
    consent_section_title: "आयुष ग्रिड डेटा साझाकरण एवं गोपनीयता सहमति",
    consent_share_profile: "सत्यापित आयुष अस्पतालों और प्रयोगशालाओं के साथ प्रोफ़ाइल साझा करें",
    consent_share_skills: "सत्यापित नियोक्ताओं के साथ कौशल मूल्यांकन वेक्टर साझा करें",
    consent_analytics: "आयुष मंत्रालय के राष्ट्रीय कार्यबल विश्लेषण में उपयोग की अनुमति दें",
    btn_save_continue: "सहेजें और मूल्यांकन जारी रखें",

    // Assessment
    assessment_title: "अनुकूली आयुष कौशल मूल्यांकन",
    assessment_subtitle: "नैदानिक प्रक्रियाओं, भेषजगुण मानकीकरण और डिजिटल स्वास्थ्य दक्षताओं का मूल्यांकन करें।",
    q_panchakarma: "शिरोधरा तेल प्रवाह और तापमान को नियंत्रित करने में आपका आत्मविश्वास कितना है?",
    q_nadi: "क्या आप नाड़ी परीक्षा के माध्यम से गति और त्रिदोष असंतुलन की पहचान कर सकते हैं?",
    q_hplc: "क्या आपने हर्बल अर्क में मार्कर यौगिकों के परीक्षण के लिए HPLC/HPTLC का उपयोग किया है?",
    q_gmp: "क्या आप शेड्यूल टी जीएमपी प्रलेखन और बैच विनिर्माण रिकॉर्ड (BMR) से परिचित हैं?",
    q_emr: "क्या आपने आयुष ग्रिड / नमस्ते पोर्टल सॉफ्टवेयर में नैदानिक डेटा दर्ज किया है?",
    lvl_none: "कोई अनुभव नहीं",
    lvl_basic: "बुनियादी (अवलोकन किया)",
    lvl_intermediate: "मध्यवर्ती (सहायता की)",
    lvl_advanced: "उन्नत (मार्गदर्शन में निष्पादित)",
    lvl_expert: "विशेषज्ञ (स्वतंत्र महारत)",
    btn_submit_assessment: "मूल्यांकन जमा करें और तैयारी वेक्टर बनाएं",

    // Opportunities & Filters
    filter_all: "सभी अवसर",
    filter_internship: "इंटर्नशिप",
    filter_micro: "माइक्रो-इंटर्नशिप (NSQF)",
    filter_faculty: "संकाय प्रशिक्षण",
    filter_remote: "केवल रिमोट",
    btn_apply: "1-क्लिक आवेदन करें",
    btn_applied: "आवेदन किया गया",
    match_score: "एआई मिलान स्कोर",
    stipend_per_month: "/ माह",
    duration_weeks: "सप्ताह",

    // e-Logbook
    logbook_title: "दक्षता-मैप की गई ई-लॉगबुक (CBME / DOAP)",
    logbook_subtitle: "प्रदर्शित (D), अवलोकन (O), सहायता (A), निष्पादन (P) नैदानिक मामले जिन्हें संकाय द्वारा अनुमोदित किया जाता है।",
    btn_log_procedure: "नैदानिक प्रक्रिया दर्ज करें",
    th_code: "कोड",
    th_competency: "दक्षता का नाम",
    th_domain: "डोमेन",
    th_doap_level: "DOAP स्तर",
    th_count: "प्रक्रिया संख्या",
    th_status: "संकाय सत्यापन",
    status_approved: "संकाय द्वारा अनुमोदित",
    status_pending: "समीक्षा लंबित",
    privacy_notice: "अनिवार्य गोपनीयता: मैं पुष्टि करता हूं कि इस लॉग में कोई मरीज-पहचान योग्य जानकारी शामिल नहीं है।"
  },

  ta: {
    // Brand & Nav
    portal_title: "ஆயுஷ் ஸ்கில் பிரிட்ஜ்",
    portal_tagline: "ஆயுஷ் அமைச்சகம் – அகில இந்திய ஆயுர்வேத நிறுவனம் (SIH26044)",
    nav_ayursetu: "ஆயுர்சேது",
    nav_colleges: "சரிபார்க்கப்பட்ட கல்லூரிகள்",
    nav_verify: "சான்றிதழ் சரிபார்ப்பு",
    nav_home: "முகப்பு",
    nav_assessment: "திறன் மதிப்பீடு",
    nav_gap_analysis: "திறன் இடைவெளி பகுப்பாய்வு",
    nav_opportunities: "வாய்ப்புகள்",
    nav_applications: "எனது விண்ணப்பங்கள்",
    nav_logbook: "மின்-பதிவேடு",
    nav_passport: "திறன் பாஸ்போர்ட்",
    nav_org_portal: "தொழில்துறை தளம்",
    nav_dept_dashboard: "துறை தகவல் பலகை",
    nav_admin: "அமைச்சக நிர்வாகி",
    switch_persona: "பயனர் மாற்றம் (டெமோ)",

    // Landing Page
    hero_badge: "ஸ்மார்ட் இந்தியா ஹேக்கத்தான் 2026 • SIH26044",
    hero_title: "ஆயுஷ் திறன் மேப்பிங், இன்டர்ன்ஷிப் மற்றும் சரிபார்க்கப்பட்ட பணிக்கான கல்வி-தொழில்துறை ஒத்துழைப்பு தளம்",
    hero_subtitle: "AI திறன் வரைபடம், CBME மின்-பதிவேடு மற்றும் W3C சரிபார்க்கக்கூடிய சான்றுகளுடன் ஆயுஷ் கல்வி மற்றும் தொழில்துறை தேவைகளை இணைக்கிறது.",
    cta_get_started: "மாணவராக தொடங்குக",
    cta_explore_opps: "வாய்ப்புகளை காண்க",
    cta_post_opp: "வாய்ப்பை இடுகையிடுக",
    stat_students: "2,400+ செயலில் உள்ள மாணவர்கள்",
    stat_institutions: "120+ ஆயுஷ் கல்லூரிகள்",
    stat_industry: "85+ சரிபார்க்கப்பட்ட கூட்டாளர்கள்",
    stat_credentials: "4,100+ வழங்கப்பட்ட சான்றிதழ்கள்",

    // Onboarding
    onboard_title: "மாணவர் சேர்க்கை & ஒப்புதல் மேலாண்மை",
    onboard_subtitle: "ஆயுஷ் கிரிட் மற்றும் ABDM நெறிமுறைகளுடன் முழு ஒப்புதல் கட்டுப்பாடு.",
    label_fullname: "முழு பெயர்",
    label_email: "மின்னஞ்சல் முகவரி",
    label_phone: "தொலைபேசி எண்",
    label_stream: "ஆயுஷ் பிரிவு",
    label_year: "கல்வி ஆண்டு",
    label_city: "நகரம்",
    label_state: "மாநிலம்",
    label_abha_id: "ஆபா அடையாள எண் (ABHA ID)",
    abha_placeholder: "91-4521-8890-1234",
    abha_verify_btn: "ABHA மூலம் சரிபார்க்கவும்",
    abha_verified_badge: "ABHA சரிபார்க்கப்பட்டது",
    consent_section_title: "ஆயுஷ் கிரிட் தரவு பகிர்வு & தனியுரிமை ஒப்புதல்கள்",
    consent_share_profile: "சரிபார்க்கப்பட்ட ஆயுஷ் மருத்துவமனைகளுடன் விவரங்களை பகிரவும்",
    consent_share_skills: "திறன் மதிப்பீட்டை வேலை வழங்குனர்களுடன் பகிரவும்",
    consent_analytics: "தேசிய ஆயுஷ் திறன் பகுப்பாய்வுக்கு அனுமதியளிக்கவும்",
    btn_save_continue: "சேமித்து மதிப்பீட்டிற்கு செல்க",

    // Assessment
    assessment_title: "தழுவல் ஆயுஷ் திறன் மதிப்பீடு",
    assessment_subtitle: "மருத்துவ நடைமுறைகள் மற்றும் டிஜிட்டல் சுகாதார திறன்களை மதிப்பிடுக.",
    q_panchakarma: "சிரோதாரா எண்ணெய் வெப்பநிலை மற்றும் ஓட்டத்தை அமைப்பதில் உங்கள் திறன் நிலை என்ன?",
    q_nadi: "நாடி பரிசோதனை மூலம் நாடி நிலையை கண்டறிய முடியுமா?",
    q_hplc: "மூலிகை தரக்கட்டுப்பாட்டிற்கு HPLC/HPTLC கருவியை இயக்கியுள்ளீர்களா?",
    q_gmp: "மருந்து உற்பத்தி விதிமுறைகள் (GMP Schedule T) மற்றும் BMR பற்றி அறிவீர்களா?",
    q_emr: "ஆயுஷ் கிரிட் மற்றும் நமஸ்தே போர்ட்டல் அமைப்புகளில் தரவு உள்ளீடு செய்துள்ளீர்களா?",
    lvl_none: "முன்அனுபவம் இல்லை",
    lvl_basic: "அடிப்படை (பார்த்தறிந்தது)",
    lvl_intermediate: "இடைநிலை (உதவியாக இருந்தது)",
    lvl_advanced: "மேம்பட்ட (வழிகாட்டுதலில் செய்தது)",
    lvl_expert: "நிபுணர் (சுயாதீனமாக செய்தது)",
    btn_submit_assessment: "மதிப்பீட்டை சமர்ப்பிக்கவும்",

    // Opportunities & Filters
    filter_all: "அனைத்து வாய்ப்புகள்",
    filter_internship: "இன்டர்ன்ஷிப்",
    filter_micro: "மைக்ரோ-இன்டர்ன்ஷிப் (NSQF)",
    filter_faculty: "ஆசிரியர் பயிற்சி",
    filter_remote: "தொலைதூர பணி மட்டும்",
    btn_apply: "1-கிளிக் விண்ணப்பிக்கவும்",
    btn_applied: "விண்ணப்பிக்கப்பட்டது",
    match_score: "AI பொருத்த மதிப்பு",
    stipend_per_month: "/ மாதம்",
    duration_weeks: "வாரங்கள்",

    // e-Logbook
    logbook_title: "திறன்-வரைபட மின்-பதிவேடு (CBME / DOAP)",
    logbook_subtitle: "மருத்துவ சிகிச்சை பதிவுகள் மற்றும் ஆசிரியர்களின் ஒப்புதல்.",
    btn_log_procedure: "மருத்துவ சிகிச்சையை பதிவு செய்க",
    th_code: "குறியீடு",
    th_competency: "திறன் பெயர்",
    th_domain: "பிரிவு",
    th_doap_level: "DOAP நிலை",
    th_count: "செயல்முறைகள் எண்ணிக்கை",
    th_status: "ஆசிரியர் ஒப்புதல்",
    status_approved: "ஆசிரியரால் அங்கீகரிக்கப்பட்டது",
    status_pending: "மதிப்பாய்வு நிலுவையில் உள்ளது",
    privacy_notice: "தனியுரிமை உறுதிமொழி: இதில் நோயாளியின் அடையாளம் வெளிப்படுத்தும் தகவல் எதுவும் இல்லை என உறுதி செய்கிறேன்."
  }
};

export function getTranslation(lang: SupportedLanguage, key: string): string {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;
}
